apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: {{ .Values.namespace }}
  labels:
    app: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
  - port: {{ .Values.frontend.service.nodePort | default .Values.frontend.port }}
    targetPort: {{ .Values.frontend.port }}
    protocol: TCP
    name: http
  {{- if eq .Values.frontend.service.type "NodePort" }}
    nodePort: {{ .Values.frontend.service.nodePort }}
  {{- end }}
  selector:
    app: frontend
